# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complex.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("complex.proto", :syntax => :proto3) do
    add_message "example.complex.ComplexMessage" do
      optional :one_dummy, :message, 2, "example.complex.DummyMessage"
      repeated :multiple_dummy, :message, 3, "example.complex.DummyMessage"
    end
    add_message "example.complex.DummyMessage" do
      optional :id, :int32, 1
      optional :name, :string, 2
    end
  end
end

module Example
  module Complex
    ComplexMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.complex.ComplexMessage").msgclass
    DummyMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.complex.DummyMessage").msgclass
  end
end
